name: Auto Commit Daily 🚀

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute tous les jours à minuit UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update File
        run: echo "Mise à jour automatique du $(date)" >> update.log

      - name: Commit and Push
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "YourGitHubUsername"
          git add .
          git commit -m "Mise à jour automatique - $(date)"
          git push
